### ISSUE TITLE
Task: Organiser prochain atelier de saisie de données avec bureaux partenaires

### ISSUE THREAD

**Issue by emmnull** [CUPUM/nplex-organisation#10]
## Objectif

Cet exercice servira à tester la saisie de données avec les firmes d'architectes, qui représentent un groupe d'utilisateurs clés. Les discussions et les test d'une première version de nplex devraient permettre d'identifier les problèmes de l'interface de saisie des données, ainsi que la disponibilité des informations demandées par la plateforme. L'expertise des membres des firmes d'architecture nourrira également des discussions autour des fiches de projets et du guide d'exemplarité / des bonnes pratiques des projets. 

### Déroulement

> Avant l'Atelier, les firmes auront préparé les informations sur un ou 2 projets

 - Explication du déroulement des séances
 - Présentation du projet appuyée sur navigation de l'application **30 minutes** (Présentation de 20 minutes, 10 min pour questions)
   -  À développer
  - Survol en groupe du guide d'exemplarité et commentaires **30 minutes** (20 minutes de présentation, 10 minutes de questions et de discussion)
    - Est-ce que les exigences du guide d'exemplarité sont réalistes à votre avis?
    - Y-a-t 'il des critères importants qui ont été oubliés?
  - Saisie des données semi-autonome par les architectes et commentaires **30 minutes**
    - Réponse aux questions générales

### Participants

| Participant | Affiliation | Rôle |
|--- | --- | --- |
| Shin Koseki | CUPUM | Animateur |
| Emmanuel Beaudry Marchand | CUPUM | Animateur |
| Autre agent ou auxiliaire de recherche? | CUPUM | Animateur |
| Participant.e. 1 | Firme 1 | Participant |
| Participant.e. 2 | Firme 1 | Participant |
| Participant.e. 3 | Firme 2 | Participant |
| Participant.e. 4 | Firme 3 | Participant |
| Participant.e. 5 | Firme 3 | Participant |
| Participant.e. 6 | Firme 4 | Participant |
| Participant.e. 7 | Firme 5 | Participant |
| Participant.e. 8 | Firme 6 | Participant |

### Matériel 

- Salle LIP ou autre salle de rencontre
  -  Écran central
- Ordinateurs portables ou tablettes grand format pour permettre aux participants d'interagir avec l'application
- Application pour enregistrement de l'écran et du microphone afin d'étudier UX et réactions

### Déroulement

> Une séance par firme (6 séances en tout)

  - Retour sur les difficultés rencontrées à la première séance **20 minutes**
    - Quels sont les éléments de la fiche de projet pour lesquels on n'avait pas d'information?
    - Quels ont été les problèmes rencontrés
  - Complétion de la saisie des données avec accompagnement **40 minutes**
    - Montage d'une ou deux fiches de projet par firme
    - Résolution des problèmes
   
### Participants pour chaque séance

| Participant | Affiliation | Rôle |
|--- | --- | --- |
| Emmanuel Beaudry Marchand | CUPUM | Animateur |
| Autre agent ou auxiliaire de recherche? | CUPUM | Animateur |
| Participant.e. 1 | Firme n | Participant |
| Participant.e. 2 | Firme n | Participant |

### Matériel
- Salle LIP ou autre salle de rencontre
  -  Écran central
- Ordinateurs portables ou tablettes grand format pour permettre aux participants d'interagir avec l'application
- Application pour enregistrement de l'écran et du microphone afin d'étudier UX et réactions

## Tasks

- [ ] [Message d'invitation](https://udemontreal-my.sharepoint.com/:w:/g/personal/emmanuel_beaudry_marchand_umontreal_ca/EYFuCt0MSN9PhOHJa-AkdhMBzgtee2LIRiA2T3KHXVVMHw?e=9lmQk2)
  - Acceptent-ils d'être enregistrés?
  - Fiche d'aide aux architectes dans la préparation des données avant l'atelier

- [ ] Présentation [(figma)](https://www.figma.com/file/CTOK91eEnegwRmM68ygj5m/Presentations?node-id=603%3A988)

- [ ] Accréditation (#56)

**Comment by AgathePC** [comment]
@iolyd je t'ai envoyé une demande d'édition du documents Figma avec les présentations
