### ISSUE TITLE
Task: Approuver la reddition de compte et procéder au dépôt final

### ISSUE THREAD

**Issue by emmnull** [CUPUM/nplex-organisation#20]
# Task Description

Il faut déposer la reddition de compte pour le deuxième paiement. Voici le document que je prévois remettre à J. De Guire: 
https://udemontreal-my.sharepoint.com/:w:/r/personal/emmanuel_beaudry_marchand_umontreal_ca/Documents/CUPUM/Nplex/Financement/[reddition_de_compte-2-31032023.docx](https://udemontreal-my.sharepoint.com/:w:/r/personal/emmanuel_beaudry_marchand_umontreal_ca/Documents/CUPUM/Nplex/Financement/reddition_de_compte-2-31032023.docx?d=w4073eadb2a79429295c77efd290c880f&csf=1&web=1&e=TTT1Pg)?d=w4073eadb2a79429295c77efd290c880f&csf=1&web=1&e=TTT1Pg

# List of actions
- [x] Action: revoir d’après commentaire de @sjinko
- [x] Valider
- [x] Envoyer à J. De Guire (et P. Marmen en cc?)

**Comment by sjinko** [comment]
Salut,

Je propose qu’on indique plutôt que nous avons décidé de ne pas faire les ateliers avec les tables de quartiers et sites organisations parce que ces activités se sont avérées inutiles en cours de projet.

Il faut faire passer le taux de complétion à 100%. Et indiquer que la mise en ligne des projets est en cours de validation par les parties.

Transformer les « obstacles » et « difficultés » en choix dans la mesure du possible.

Le rapport est trop négatif. Il faut plutôt de réjouir que le projet soit finalisé.
________________________________
From: Emmanuel Beaudry Marchand ***@***.***>
Sent: Friday, March 31, 2023 16:19
To: CUPUM/nplex-organisation ***@***.***>
Cc: Shin Koseki ***@***.***>; Assign ***@***.***>
Subject: [CUPUM/nplex-organisation] Task: Approuver la reddition de compte et procéder au dépôt final (Issue #20)


Task Description

Il faut déposer la reddition de compte pour le deuxième paiement. Voici le document que je prévois remettre à J. De Guire:
https://udemontreal-my.sharepoint.com/:w:/r/personal/emmanuel_beaudry_marchand_umontreal_ca/Documents/CUPUM/Nplex/Financement/[reddition_de_compte-2-31032023.docx](https://udemontreal-my.sharepoint.com/:w:/r/personal/emmanuel_beaudry_marchand_umontreal_ca/Documents/CUPUM/Nplex/Financement/reddition_de_compte-2-31032023.docx?d=w4073eadb2a79429295c77efd290c880f&csf=1&web=1&e=TTT1Pg)?d=w4073eadb2a79429295c77efd290c880f&csf=1&web=1&e=TTT1Pg<https://can01.safelinks.protection.outlook.com/ap/w-59584e83/?url=https%3A%2F%2Fudemontreal-my.sharepoint.com%2F%3Aw%3A%2Fr%2Fpersonal%2Femmanuel_beaudry_marchand_umontreal_ca%2FDocuments%2FCUPUM%2FNplex%2FFinancement%2F%255Breddition_de_compte-2-31032023.docx%255D(https%3A%2F%2Fudemontreal-my.sharepoint.com%2F%3Aw%3A%2Fr%2Fpersonal%2Femmanuel_beaudry_marchand_umontreal_ca%2FDocuments%2FCUPUM%2FNplex%2FFinancement%2Freddition_de_compte-2-31032023.docx%3Fd%3Dw4073eadb2a79429295c77efd290c880f%26csf%3D1%26web%3D1%26e%3DTTT1Pg)%3Fd%3Dw4073eadb2a79429295c77efd290c880f%26csf%3D1%26web%3D1%26e%3DTTT1Pg&data=05%7C01%7Cshin.koseki%40umontreal.ca%7Cabb9547185904b405a3a08db32253d07%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C638158908255916108%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FukEPGcGF53%2B9jQEsSaGh5wkb0vJcFhXm1qFbQOWZPA%3D&reserved=0>

List of actions

  *    Valider
  *    Envoyer à J. De Guire (et P. Marmen en cc?)

**Comment by sjinko** [comment]
.. de manière générale, il fait bien montrer à la
Ville en quoi les 1750 heures de travail quelle a payé ont été un bon investissement.

Montrer aussi les contributions additionnelles obtenues pour la suite (10k inven_t, 50k Umontreal partenariats), et l’intérêt généré chez les bureaux d’architecte et dans les bureaux des permis et autres instances de la ville via les membres du CC
________________________________

**Comment by emmnull** [comment]
D'accord, j'apporte les modification directement dans la version sur le drive google.
