### ISSUE TITLE
Task: Reprendre contact avec le comité de conseil

### ISSUE THREAD

**Issue by emmnull** [CUPUM/nplex-organisation#3]
# Task Description

L'addenda au projet obtenu en décembre prévoit la tenue d'un atelier avec le comité de conseil dès janvier 2023. Les activités de cet atelier sont esquissées ici: #11 .

Avant tout, nous devons d'abord reprendre contact avec le comité de conseil et valider sa composition. Pour ce dernier point, nous devons confirmer si J. Trudel est toujours en position de participer malgré son changement de poste, et nous devons aussi inviter O. Gauthier référencé par S-UWA l'été dernier. (#5)

### Matériel

Nous avons préparé un modèle de lettre pour reprendre contact avec les membres du comité de conseil et les inviter au prochain atelier:

https://udemontreal-my.sharepoint.com/:w:/r/personal/emmanuel_beaudry_marchand_umontreal_ca/_layouts/15/Doc.aspx?sourcedoc=%7BBEB507FA-661C-452F-B5BF-433617354E73%7D&file=nplex-invitation_atelier-comite_conseil.docx&action=default&mobileredirect=true

### Contacts

Membres actifs du comité:

- Elise Lacoursiere Bourget: elise.lacoursierebourget@montreal.ca
- Julien Rozon: julien.rozon@montreal.ca
- Sebastien Aumais: sebastien.aumais@montreal.ca
- Mathias Losco: mathias.losco@montreal.ca (n'a pas encore participé à un atelier, mais a déjà été invité sur le comité)

Nouveaux membres à inviter sur le comité (et à l'atelier)

- Olivier Gauthier: olivier.gauthier@montreal.ca (référé par le partenaire S-UWA, n'a pas encore été invité)

Membres à confirmer (@iolyd)

- Jeanne Trudel: jeanne.leblanc-trudeau@montreal.ca

# List of actions

- [x] Rédiger lettre de reprise de contact avec comité de conseil
- [x] Valider
- [x] @iolyd Confirmer avec J. Trudel si participation toujours possible malgré changement de poste, valider absence de conflit d'intérêt (travaille désormais pour le bureau du design)
- [x] #5
- [x] Envoyer invitations

**Comment by emmnull** [comment]
@Sarahprairie, j'ai ajouté plus d'information dans la description ci-haut, dont une première version de lettre d'invitation que je t'inviterais à réviser lorsque tu auras du temps. Nous devrons envoyer les invitations bientôt car la tenue de l'atelier (#11) avec le comité de conseil est un prérequis pour satisfaire la Ville et obtenir le prochain paiement de la subvention.

Je te reviens bientôt pour qu'on regarde ensemble la préparation de l'atelier. Entretemps, laisse-moi savoir si jamais tu as des questions, je me rendrai dispo pour une rencontre ou un appel. Merci!

**Comment by Sarahprairie** [comment]
Salut @iolyd ! Peux-tu m'envoyer le lien Doodle avec les disponibilités pour l'atelier 3 ?

**Comment by emmnull** [comment]
Oui! Désolé pour le délai: https://doodle.com/meeting/participate/id/dNOyrkKe

**Comment by emmnull** [comment]
Salut @Sarahprairie, j'ai complété la description du issue avec la liste de contact à qui envoyer l'invitation. Je m'occupe de confirmer auprès de Jeanne.

**Comment by emmnull** [comment]
Je ferme ce issue désormais complété: des rencontres ont été coordonnées pour les membres actif du comité-conseil et leur tenue est déjà débutée.

Related: https://github.com/CUPUM/nplex/issues/143
